src/org/myrobotlab/service/OpenCV.java
add method for publishRecognizedFace
=> Update OpenCV.java add method for publishRecognizedFace

src/org/myrobotlab/service/MicrosoftSpeech.java
Reverts MyRobotLab/myrobotlab#49
I'd recommend creating a new method if needed. Do not overload setLanguage for something else.
=> Revert "Update MicrosoftSpeech.java"

src/org/myrobotlab/service/TesseractOcr.java
This should get merged into Master and will make Mac users happier :)
=> fixed TesseractOcr to see mac as linux POSIX class

src/main/java/org/myrobotlab/service/LocalSpeech.java
LocalSpeech uses festival for Linux
=> maybe easy implementation of festival for raspi (and other Linux)

src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/JMonkeyEngine.java
https://github.com/MyRobotLab/myrobotlab/issues/256
=> Fix race condition for jme3 / virtual inmoov

src/main/java/org/myrobotlab/framework/Service.java, src/main/java/org/myrobotlab/framework/interfaces/ServiceInterface.java, src/main/java/org/myrobotlab/service/Arduino.java, src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/Runtime.java, src/main/java/org/myrobotlab/service/Serial.java
Merge request so that the shutdown event can notify all services of impending shutdown.
InMoov now can do whatever it needs to before Arduinos and Servos are shutdown.
=> Low level Services should be unaware of high level Services #264

pom.xml, src/main/java/org/myrobotlab/i2c/AdafruitLEDBackpack.java, src/main/java/org/myrobotlab/i2c/I2CFactory.java, src/main/java/org/myrobotlab/i2c/I2CProxyDeviceImpl.java, src/main/java/org/myrobotlab/service/RasPi.java
updated pi4j-core to 1.2-SNAPSHOT and forced wiringPi implementation
https://github.com/MyRobotLab/myrobotlab/issues/262
=> desperate fixes to get raspi + i2c worky again

src/main/java/org/myrobotlab/service/KeyboardSim.java
This service allows to simulate KeyboardEvents (Key-Presses & Key-Releases) and provides some useful helper-methods (Key-combinations & combined press&release).
If you have an idea for a better name, please change it.
This service currently doesn't have an unit test, because I had no idea how to test it (checking if the key is actually pressed - maybe?).
This PR doesn't target Nixie, maybe Ogre.
Related PR: #282
=> new service: KeyboardSimulator

src/main/java/org/myrobotlab/service/Python.java
this thing + sraix will save tone off code lines / aiml things
( eval() seem not enought and didn't want to touch / break it )
https://github.com/MyRobotLab/myrobotlab/issues/85
=> evalAndWait for a python return statement inside aiml

src/main/java/org/myrobotlab/service/MouseSim.java
This service allows to simulate MouseEvents (Button-Presses & Button-Releases) and provides some useful helper-methods (Button-combinations & combined press&release) as well as options to move the mouse and scroll the wheel.
If you have an idea for a better name, please change it.
This service currently doesn't have an unit test, because I had no idea how to test it (checking if the button is actually pressed - maybe?).
This PR doesn't target Nixie, maybe Ogre.
Related PR: #281
=> new service: MouseSimulator

src/main/java/org/myrobotlab/opencv/OpenCVFilter.java, src/main/java/org/myrobotlab/opencv/OpenCVFilterYolo.java, src/main/java/org/myrobotlab/opencv/VideoProcessor.java
Idea, is : 
- If there is a thread running by filter, terminate it , if filter is removed..
- Fix lastSoureKey for filters, it was broken !
Todo : understand why there is still some things in memory after killed the filter ...
=> OpenCV filters mods :

src/main/java/org/myrobotlab/framework/Service.java
set isReady projected member to appropriate value
=> added isReady as protected member ... implementing service can override

pom.xml, src/main/java/org/myrobotlab/service/AudioFile.java, src/main/java/org/myrobotlab/service/JMonkeyEngine.java
https://github.com/MyRobotLab/myrobotlab/issues/318
=> Ogg support in right place

src/main/java/org/myrobotlab/codec/ApiFactory.java, src/main/java/org/myrobotlab/framework/Instantiator.java, src/main/java/org/myrobotlab/framework/Service.java, src/main/java/org/myrobotlab/service/Arduino.java, src/main/java/org/myrobotlab/service/SwingGui.java
maybe subjective…
try to reduce little by little the level of information for INFO
https://github.com/MyRobotLab/myrobotlab/issues/308
=> some log.info to log.debug 

src/main/java/org/myrobotlab/service/MouseSim.java
This pr is a follow up to #282 and resolves most of the suggestions mentioned there.
It doesn't include a way to target specific buttons directly (as per @supertick's [comment](https://github.com/MyRobotLab/myrobotlab/pull/282#issuecomment-427043761), I still want to add this functionality, but wanted to get this quality-of-code update finally out first.
=> MouseSim: improvements

src/main/java/org/myrobotlab/kinematics/DruppIKSolver.java, src/main/java/org/myrobotlab/service/DruppNeck.java, src/test/java/org/myrobotlab/kinematics/DruppIKSolverTest.java
this is the initial cut at the drupp neck service..    i really don't know how it works.
=> Drupp penguin ik

src/main/java/org/myrobotlab/framework/repo/IvyWrapper.java, src/main/java/org/myrobotlab/framework/repo/MavenWrapper.java, src/main/java/org/myrobotlab/framework/repo/Repo.java, src/main/java/org/myrobotlab/service/ProgramAB.java, src/main/java/org/myrobotlab/service/Runtime.java, src/main/java/org/myrobotlab/swing/ServoGui.java
fixes #283 
save was not broken, but "auto save" was removed.
I re-added auto save on shutdown, AND added it to the "save" for the servo gui, since that seems logical.
However, auto-load has been disabled and going forward I think most agreed with not doing this.  The complexity of some services and the issues of returning to a valid running state with previously saved data can be very complex.  {some service}.load()  will continue to be supported, but this will not automatically get called when the service starts.
I verified both auto-save and manual-load are worky.
=> #283 serialisation issues

src/main/java/org/myrobotlab/framework/repo/IvyWrapper.java, src/main/java/org/myrobotlab/framework/repo/MavenWrapper.java, src/main/java/org/myrobotlab/framework/repo/Repo.java, src/main/java/org/myrobotlab/service/Runtime.java
Confirmed that multiple "installs" can be going on simultaneously. No
marked install as synchronized in all repo implementations. closes #331
=> #331 - installation issue

src/main/java/org/myrobotlab/framework/repo/IvyWrapper.java, src/main/java/org/myrobotlab/framework/repo/MavenWrapper.java, src/main/java/org/myrobotlab/framework/repo/Repo.java, src/main/java/org/myrobotlab/service/ProgramAB.java, src/main/java/org/myrobotlab/service/Runtime.java
fixed - IvyWrapper & MavenWrapper are now serializable
=> #330 remote adapter service fail serialization of runtime

src/main/java/org/myrobotlab/programab/MrlSraixHandler.java, src/test/java/org/myrobotlab/service/ProgramABTest.java, src/test/resources/ProgramAB/bots/lloyd/aiml/lloyd.aiml
This should resolve issue #335
=> restoring default behavior to call out to pannous for sraix calls.

pom.xml, src/main/java/org/myrobotlab/opencv/OpenCVFilter.java, src/main/java/org/myrobotlab/opencv/OpenCVFilterFaceDetectDNN.java, src/main/java/org/myrobotlab/opencv/OpenCVFilterLloyd.java, src/main/java/org/myrobotlab/opencv/OpenCVFilterYolo.java, src/main/java/org/myrobotlab/service/Deeplearning4j.java, src/main/java/org/myrobotlab/service/OpenCV.java, src/test/java/org/myrobotlab/opencv/OpenCVFilterFaceDetectDNNTest.java
let's try that again... dl4j upgrade to 1.0.0-beta3 / javacv to 1.4.3 .
adding caffe based face recognizer filter for opencv.
=> Opencv dnn face detect

src/main/java/org/myrobotlab/opencv/OpenCVFilterKinectDepth.java, src/main/java/org/myrobotlab/service/OpenCV.java
Removed Kinect specific grabber from OpenCV
Added kinect grabber to OpenCVFilterKinectDepth
=> OpenCV Kinect

src/main/java/org/myrobotlab/service/BodyPart.java
It was missing, just pasted existing things from inmoov arm Inside generic bodypart, for future tests.
I never used it yet, don't know every details…
=> Implement kinematics class inside bodypart based on inmoov arm service

src/main/java/org/myrobotlab/service/TesseractOcr.java
minor issue to make sure we don't pull in old versions of javacpp
=> updating dependencies to be in line with javacpp 1.4.3

src/main/java/org/myrobotlab/framework/Service.java, src/main/java/org/myrobotlab/framework/interfaces/ServiceInterface.java, src/main/java/org/myrobotlab/service/Runtime.java
=> loadAndStart !

src/main/java/org/myrobotlab/service/OpenCV.java, src/test/java/org/myrobotlab/service/OpenCVTest.java
sorry, missed this because i was too eager to merge i guess.. twitchy fingers after lots of coffee.
=> fixed transition states file -> camera -> file -> camera

src/main/java/org/myrobotlab/opencv/MJpegFrameGrabber.java
small NPE check to fix the mjpeg frame grabber..
=> small NPE check to fix #371

src/main/java/org/myrobotlab/service/Arduino.java
=> ensuring that the serial port is started before calling connect.

src/main/java/org/myrobotlab/inmoov/Utils.java, src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/InMoov2.java, src/main/java/org/myrobotlab/service/Python.java
Use class for loadGestures(), no refactor. 
Also add stopGesture() to stop a running gesture ( big red buton ! )
=> Load gestures

src/main/java/org/myrobotlab/service/ProgramAB.java
This seems like a regression.  I'm not sure what introduced this bug in the first place.  This will make it more robust in the future.  
we should revisit how program ab initializes it's directory structure when we re-org the resources and data directories.
=> not sure if this fixes the exception that gael was seeing.  hopefully.

src/main/java/org/myrobotlab/service/OpenCV.java
possibility to launch last config used for opencv, if we loadAndStart() .
=> Possibility to launch last config used for opencv

src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/Sweety.java, src/main/java/org/myrobotlab/service/Tracking.java
Ohh. I was refactactoring how InMoov use opencv filters but discovered tracking was broken.
This is intermediate PR
I fixed it by calculating the image dimentions to fit the range logic ( 0 > 1 ) for PID compute.
I took the opportunity to clean up things :
We should attach ServoControl to tracking service instead of using arduino + servo peers, that is better, for logic and custom hardware use.
Removing filters from tracking service is dangerous, let the user decide what he need. And add a filter only if it is necessary.
Some things can be further improved
Lktracking not yet tested/fixed, only facedetect on the robot.
Expertise from some tracking gurus is welcome !
https://github.com/MyRobotLab/myrobotlab/issues/389
=> Fix facedetect & big clean up :

src/main/java/org/myrobotlab/service/WebkitSpeechRecognition.java, src/main/resources/resource/WebGui/service/js/WebkitSpeechRecognitionGui.js
Fix lockOutAllGrammar for universal use ( was no worky if ear attached to programAB )
Want to used it after pushed some stuff from py to java land
=> Fix lockOutAllGrammar

src/main/java/org/myrobotlab/service/InMoov.java
, exception can be seen here……:  http://myrobotlab.org/myrobotlab_log/upload/hairygael/1544996545.myrobotlab.log
This patch makes the startOpenCV return a boolean.  This will address the exception seen in the log file.
=> interm fix for latest no worky from gael

src/main/java/org/myrobotlab/service/Servo.java
https://github.com/MyRobotLab/myrobotlab/issues/408
removed lastPos = targetPos; from moveTo() , this is already called after movement reached
=> MoveToBlocking is back again

src/main/java/org/myrobotlab/opencv/OpenCVFilterLKOpticalTrack.java, src/main/java/org/myrobotlab/service/AndroidSpeechRecognition.java, src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/Pid.java, src/main/java/org/myrobotlab/service/Tracking.java
- Compute frame height/width for int/float
- Add a rest() + clearpoint() at start / stop to avoid fast head moves
- Fix PID buffer overrun ( that will burned CPU to 100% sometime )
https://github.com/MyRobotLab/myrobotlab/issues/389
=> fix Lktracking

src/main/java/org/myrobotlab/service/InMoov.java
Let set unit test to GREEN 
https://github.com/MyRobotLab/myrobotlab/issues/377
=> deprecated & warn some inmoov methods

src/main/java/org/myrobotlab/service/SwingGui.java
use SwingGui.maximize() from InMoov if you want the gui to maximize
=> SwingGui.maximize()

src/main/java/org/myrobotlab/programab/MrlSraixHandler.java, src/main/java/org/myrobotlab/programab/OOBPayload.java, src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/ProgramAB.java, src/test/java/org/myrobotlab/service/ProgramABTest.java, src/test/resources/ProgramAB/bots/lloyd/aiml/lloyd.aiml
pull request that does massive refactor/cleanup of programab.  unit test still passes.  new test added.  This change is to ensure support that one programab service can run multiple bots.  Each bot can have multiple sessions with users.
=> Programab 419

src/main/java/org/myrobotlab/codec/CodecJson.java
this might be overkill.. but hopefully this fixes the concurrent mod exceptions that we have been seeing lately.
=> aggressively synchronize all serialization.

pom.xml, src/main/java/org/myrobotlab/arduino/ArduinoUtils.java, src/main/java/org/myrobotlab/framework/Platform.java, src/main/java/org/myrobotlab/framework/repo/ServiceData.java, src/main/java/org/myrobotlab/image/Util.java, src/main/java/org/myrobotlab/io/FileIO.java, src/main/java/org/myrobotlab/io/Zip.java, src/main/java/org/myrobotlab/jme3/InMoov3DApp.java, src/main/java/org/myrobotlab/oculus/OculusDisplay.java, src/main/java/org/myrobotlab/opencv/OpenCVFilterFaceRecognizer.java, src/main/java/org/myrobotlab/service/Agent.java, src/main/java/org/myrobotlab/service/Arduino.java, src/main/java/org/myrobotlab/service/AudioFile.java, src/main/java/org/myrobotlab/service/PickToLight.java, src/main/java/org/myrobotlab/service/ProgramAB.java, src/main/java/org/myrobotlab/service/Runtime.java, src/main/java/org/myrobotlab/service/ServoOrchestrator.java, src/main/java/org/myrobotlab/service/Sphinx.java, src/main/java/org/myrobotlab/service/SwingGui.java, src/main/java/org/myrobotlab/service/WebGui.java, src/main/java/org/myrobotlab/swing/AndroidSpeechRecognitionGui.java, src/main/java/org/myrobotlab/swing/ArduinoGui.java, src/main/java/org/myrobotlab/swing/IpCameraGui.java, src/main/java/org/myrobotlab/swing/SwingGuiGui.java, src/main/java/org/myrobotlab/swing/WebkitSpeechRecognitionGui.java, src/main/java/org/myrobotlab/swing/abstracts/AbstractSpeechSynthesisGui.java, src/main/java/org/myrobotlab/swing/widget/DirectionWidget.java, src/main/java/org/myrobotlab/swing/widget/DockableTab.java, src/main/java/org/myrobotlab/swing/widget/ProgressDialog.java
centralizing the resource directory into a single method (I think it is comprehensive.)  you can override the resource directory by specifying the resource.dir system property.  It does touch on some of the serviceData.json generation logic, so that should be sanity checked.
=> Resource dir

src/test/java/org/myrobotlab/service/AbstractServiceTest.java, src/test/java/org/myrobotlab/service/ProgramABTest.java
I just discovered that our Auto-testing elves for ProgramAB had been ignored!  I'm putting them back to work.  It's very important that this test continues to run.
=> putting the programab auto-testing elves back to work. 

src/test/java/org/myrobotlab/service/ProgramABTest.java
no longer will it write to the test resource directory and smudge up the source code after it runs.
=> make it so that programab test uses a junit test folder.

src/main/java/org/myrobotlab/inmoov/LanguagePack.java, src/main/java/org/myrobotlab/service/InMoov.java, src/main/java/org/myrobotlab/service/InMoovGestureCreator.java, src/main/java/org/myrobotlab/service/InMoovHand.java, src/main/java/org/myrobotlab/service/InMoovHead.java, src/main/java/org/myrobotlab/service/MarySpeech.java, src/test/java/org/myrobotlab/service/AbstractServiceTest.java, src/test/java/org/myrobotlab/service/InMoovTest.java, src/test/java/org/myrobotlab/service/ProgramABTest.java
this tests 45% of the inmoov source code.  we can always improve upon it with better assertions.
=> Inmoov unit test

pom.xml, src/main/java/org/myrobotlab/service/ProgramAB.java, src/main/java/org/myrobotlab/service/Solr.java, src/test/java/org/myrobotlab/service/SolrTest.java
additionally, the shutdown behavior of programab is now configurable..  (this change got pulled in..) default behavior is preserved.
=> update to solr 7.7.1 and adding a solr unit test

src/main/java/org/myrobotlab/audio/AudioProcessor.java, src/main/java/org/myrobotlab/service/AudioFile.java, src/test/java/org/myrobotlab/service/AudioFileTest.java, src/test/java/org/myrobotlab/service/MarySpeechTest.java
updated unit tests for maryspeech and audio file.
=> supporing mute on the audio file service.  

src/main/java/org/myrobotlab/service/OpenCV.java
bug fix - move test of virtual above package name  and only switch to image grabber if request is a hardware camera in virtual mode
=> virtual only switches to image grabber if input source is camera

src/main/java/org/myrobotlab/service/LocalSpeech.java, src/main/java/org/myrobotlab/service/abstracts/AbstractSpeechSynthesis.java
#492 - fixed parsing of files, loads everything into "name" - makes "clean" filenames directories
=> local speech fixes

src/main/java/org/myrobotlab/service/Deeplearning4j.java
small change for decoding of vgg16 predictions after 1.0.0-beta4 upgrade
=> fixing the decoding of vgg16 results for dl4j filter after 1.0.0-beta4 upgrade

Jenkinsfile, src/main/java/org/myrobotlab/framework/Platform.java, src/main/java/org/myrobotlab/framework/ProcessData.java, src/main/java/org/myrobotlab/service/Agent.java, src/main/java/org/myrobotlab/service/Runtime.java
=> Agent auto update

pom.xml, src/main/java/org/myrobotlab/framework/Service.java, src/main/java/org/myrobotlab/framework/repo/ServiceData.java, src/main/java/org/myrobotlab/io/FileIO.java, src/main/java/org/myrobotlab/service/Agent.java, src/main/java/org/myrobotlab/service/Joystick.java, src/main/java/org/myrobotlab/service/Polly.java, src/main/java/org/myrobotlab/service/Python.java, src/main/java/org/myrobotlab/service/Runtime.java, src/main/java/org/myrobotlab/service/Security.java, src/main/java/org/myrobotlab/service/Sphinx.java, src/main/java/org/myrobotlab/swing/PythonGui.java
ability to add keys via the command line - this adds them to the store and accepts -c / --config-dir to place them in {configDir}/store.
=> Add keys with cmdline

src/resource/InMoov/InMoov.minimalHead.py
=> missing fullspeed

src/main/java/org/myrobotlab/opencv/OpenCVFilterMiniXception.java, src/main/java/org/myrobotlab/service/Deeplearning4j.java, src/main/java/org/myrobotlab/service/OpenCV.java, src/main/java/org/myrobotlab/swing/opencv/OpenCVFilterMiniXceptionGui.java
this introduces a new opencv filter called "miniXception" based on the open source project here: https://github.com/omar178/Emotion-recognition 
To use this new filter, you must have the "FaceDetect" filter in the pipeline before you add the miniXception filter.
The face detector will identify a bounding box for the face.. that will be cropped and send into DL4j service that will evaluate the keras model.  The keras model returns back the emotions that were detected on the face.
Detected emotions are:  "angry" ,"disgust","scared", "happy", "sad", "surprised", "neutral"
The opencv filter has a "confidence" threshold as well as a  "boxSlop".  The confidence ( is from 0 to 100 in the gui.. actual values are between 0-1)   the boxSlop is the additional border that will be added (in pixels) to …
=> Mini exception open cv filter for emotion detection in faces.

src/main/java/org/myrobotlab/framework/Platform.java, src/main/java/org/myrobotlab/service/Runtime.java
This will attempt to recognize the bitness of the OS during startup and find mismatches between OS & JVM.
Successfully tested on 64bit Windows 7/8/8.1/10 and with 64bit JVM 8/9/10/11 & 32bit JVM 8/9 (see below for detailed information). (For JVM 9 an early version had to be used since 32bit Java 9 was apparently never intended to be a thing.)
winXP isn't really needed. On the one hand it's unsupported since the 8th of April 2014, on the other hand 64bit winXP wasn't really a thing - and you can't mismatch bitness on 32bit systems.
For Linux, it is a similar story. I've tried for about an hour to get a working 32bit JVM on a 64bit system and gave up. If it's that hard to mismatch bitness, I'm not worried. (Results from 64bit Linux are below.)
About macOS ... well, I've no idea.
64bit …
=> windows: check os bitness & compare with jvm bitness

src/main/java/org/myrobotlab/service/Adafruit16CServoDriver.java, src/main/java/org/myrobotlab/service/abstracts/AbstractMotor.java
Minor changes to make the MotorDualPwm work on Adafruit16CServoDriver
again
=> MotorDualPwm on Adafruit16CServoDriver

src/main/java/org/myrobotlab/service/Mqtt.java
adding the bots bump to Mqtt.getMetaData
=> Mqtt version bump get meta

pom.xml, src/main/java/org/myrobotlab/service/Deeplearning4j.java, src/main/java/org/myrobotlab/service/OpenCV.java, src/main/java/org/myrobotlab/service/TesseractOcr.java
=> updating javacpp dependencies to 1.5.2 (javacv/dl4j/tesseract)

src/main/resources/resource/WebGui/app/service/js/InMoov2Gui.js
This is for now, but the Activ button will be for to show if a part is Activated.
=> Swapping buttons _on.png to _Activ.png

src/main/java/org/myrobotlab/service/InMoov2.java
hopefully this is not breaking stuff, but fixing some...
=> isActivated parts fix

src/main/java/org/myrobotlab/service/InMoov2.java
the purpose is to add the servo mixer into InMoov webgui
=> adding ServoMixer

src/test/java/org/myrobotlab/opencv/OpenCVFilterFaceRecognizerTest.java
using a temp folder for training image data so re-running the same test should be deterministic and not fail if the checkout isn't clean.
=> fixing face rec test to use a temp folder for training data.

src/main/resources/resource/WebGui/app/views/tabsView.html
=> sidenav push

src/main/resources/resource/WebGui/app/service/views/WebGuiGui.html
I put it in here for temporary test
=> Proposition for Homepage html

src/main/resources/resource/WebGui/app/service/js/WebGuiGui.js
This is meant to be removed when we are good with the homepage
=> For temporary tests with homepage

src/main/java/org/myrobotlab/service/InMoov2.java
UltraSonicSensor to UltrasonicSensor
=> Webgui work

src/main/java/org/myrobotlab/service/InMoov2.java
Hopefully this doesn't hit Java in the jaw
=> ultrasonicRight and Left with extra arduino

src/main/java/org/myrobotlab/service/InMoov2.java
Initialy, I had pushed this to webgui_work branch, but it is taking long to get merged and stops me to get further.
=> reversed brain to chatbot, eye to opencv

src/main/java/org/myrobotlab/arduino/virtual/MrlCommIno.java, src/main/java/org/myrobotlab/math/interfaces/Mapper.java, src/main/java/org/myrobotlab/service/Servo.java, src/main/java/org/myrobotlab/service/interfaces/ServoControl.java, src/main/java/org/myrobotlab/service/meta/ChessGameMeta.java, src/main/java/org/myrobotlab/service/meta/GoProMeta.java, src/main/java/org/myrobotlab/service/meta/InMoov2HeadMeta.java, src/main/java/org/myrobotlab/service/meta/WiiDarMeta.java, src/main/java/org/myrobotlab/service/meta/WolframAlphaMeta.java, src/test/java/org/myrobotlab/service/ServiceInterfaceTest.java, src/test/java/org/myrobotlab/service/ServoTest.java
making sure blocking moves reschedule auto disable, also, after a blocking move a servo should be set to isMoving false.
One item of question that came up.. it seemed that  i need to wait for ~ 1 second longer than expected for the servo to disable.  I'd like us to be able to tighten that up in the future.
=> servo blocking moves
